function TesteIF(){
    let idade = prompt("Qual a sua idade?")
    if (idade >=18){
        console.log("Maior de idade")
    }else{
        console.log("Menor de idade")

        }
    }
TesteIF();

function TesteELSE(){
    let idade = prompt("Qual a sua idade?")
    if(idade<=12){
        console.log("Criança")
    }else if
        (idade >12 && idade <18){
            console.log("Adolescente")
     }else if (idade >=18 && idade<60){
        console.log("adulto")
     }else{ 
        console.log("idoso")
     }

    }
 
    